#!/bin/bash
#===========colors=========
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
echo "$(tput setaf 2) enter table name ${reset}"
read name_table
if [ -f "../database/$name_database/$name_table" ]
then
echo "$(tput setaf 2) enter word: ${reset}"
read word
sed -i "/$word/d" ../database/$name_database/$name_table
echo "$(tput setaf 2) row is deleted ${reset}"
else
echo "$(tput setaf 1) table not found ${reset}"
fi
